### PR TITLE
Made homepage fully responsive + improved ux a bit

### PR DESCRIPTION
**Pull request by Lunaversitay**
Hi, deciding to give this pull request a shot, apologies if the repo isn't accepting any right now I was just pretty bored so I decided to use up an hour to touch up mostly the main page and clean up some other stuff. I'll go in full detail about what I done below.

**Responsiveness:**
(example of tabs responsiveness can be viewed here: [https://i.lunaversity.dev/Te46kMchnv.mp4](https://i.lunaversity.dev/Te46kMchnv.mp4))
I believe responsiveness is very much key to any website, despite its launch date, so I decided to try and make the homepage (mostly the tabs) as responsive as possible without disturbing any of the custom css, thankfully you guys used tailwind so it was pretty easy.

Large screens (monitors, etc...): The tabs will pretty much look how they normally do in the main branch
Medium & Small screens (tablets/phones): The navigation tabs will go into columns to prevent squishing and/or them going off to the side of the screen. The tab content also goes into columns to prevent the same result above.

**UX Improvements**

Again pretty small but very noticeable changes, in the tab content I made the job icons basically cards that you can just click on (they also show a background when hovering) this is way easier than clicking on a small word link when the entire card is all the same context. Example below

I also added a hover background to the tab navigation buttons so it's more obvious to people what they're selecting.

That's pretty much it, sorry for the long read decided to explain everything I did since I'm a complete stranger to this repo. If you guys are open to PRs and want some extra help I'd be more than willing to help out, it's about time the balance got a fully fleshed website 👍 
(p.s. sorry if I made any inconsistencies, being fresh to this repo I don't really know the development structure you guys use)

### CODE REVIEW

**Comment by OHaiDanny** [comment]
Hey @Lunaversitay,

Thanks for working on this PR. As of now there was a homepage mobile PR that was merged this morning that were based on designer's mockups. However, your UX improvements are really nice. If you are busy at the moment, I can support bringing your UX changes for the role slider into a separate PR to be merged :)

Cheers!

**Comment by OHaiDanny** [comment]
I was playing around with the bg hover and I noticed that the hover bg needs some extra padding. However by introducing extra padding on the x-axis will push elements down. Instead I'm thinking of maybe scaling the job logo up a bit when a user hovers on each of the job "cards".

**Comment by OHaiDanny** [comment]
Something like this: https://streamable.com/rf87xh

**Comment by OHaiDanny** [comment]
Also, feel free to DM Laille on The Balance if you would like to get added as a website contributor :)

**Comment by OHaiDanny** [comment]
Oh wait! i got your bg colour changes to work with the extra padding!

(sorry about the spam I like to comment on PRs a lot xD)

**Comment by Lunaversitay** [comment]
> 
> 
> Hey @Lunaversitay,
> 
> Thanks for working on this PR. As of now there was a homepage mobile PR that was merged this morning that were based on designer's mockups. However, your UX improvements are really nice. If you are busy at the moment, I can support bringing your UX changes for the role slider into a separate PR to be merged :)
> 
> Cheers!

Hi, sorry I was out for most of the day today and just got back, glad you like the UX improvement, although I gotta say increasing the icon size is definitely a good idea for the job cards.
Sure I'll definitely message them, definitely wouldn't mind sharing a helping hand with any of the development in my freetime - thanks for PRing the ux changes by the way! 👍

**Pull request closed without merging**
