### PR TITLE
Add <head> tags to file to rendered pages

### PR DESCRIPTION
**Pull request by kaydeethree**
Rendered pages are not generating valid HTML. They also do not have <title> tags but this will take more effort to resolve

### CODE REVIEW

**Comment by OHaiDanny** [comment]
I have a PR made to address the <title> tags

**Comment by nonowazu** [comment]
@kaydeethree 

I'm fine approving this PR, but could you add those tags to the [baseof](https://github.com/The-Balance-FFXIV/glam/blob/ba601236d010b39b25f11f8e86a1667da0e604c9/layouts/_default/baseof.html#L3) template instead?

**Comment by OHaiDanny** [comment]
I'm looking at the html of the website and it looks like Hugo automatically makes the head tags? This screenshot is in https://www.thebalanceffxiv.com/

image

**Comment by nonowazu** [comment]
I think that's your browser inserting those tags @OHaiDanny –

```
wget -q -O - https://www.thebalanceffxiv.com/ | head -n 20

<!doctype html><html lang=en><meta http-equiv=content-type content="text/html" charset=utf-8>
<meta http-equiv=x-ua-compatible content="IE=edge,chrome=1">
<meta name=viewport content="width=device-width,initial-scale=1">
<link rel=preconnect href=https://fonts.googleapis.com>
<link rel=preconnect href=https://fonts.gstatic.com crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@700&family=Roboto:ital,wght@0,400;0,700;1,400&display=swap" rel=stylesheet>
<script type=text/javascript src=/js/header.js defer></script>
<link rel=stylesheet href=/css/main.min.28981f4659fe9a2954e79b41fea645bbc2572238262bee6f436156b8fd012473.css integrity=sha256-KJgfRln+milU55tB/qZFu8JXIjgmK+5vQ2FWuP0BJHM=>
<body>
<header class="bg-center bg-cover relative z-10">
<nav class=z-20>
<div class="container mx-auto px-2 md:px-0">
<div class="flex justify-center">
<div class="hidden md:flex items-center space-x-3">
<a href=# class="py-4 px-4 font-semibold text-xl text-white hover:opacity-75" title>
Combat Jobs
</a>
<a href=# class="py-4 px-4 font-semibold text-xl text-white hover:opacity-75" title>
Other Jobs
</a>
```

**Comment by nonowazu** [comment]
Superseded by #183

**Pull request closed without merging**
